# -*- coding: utf-8 -*-
"""prodigy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5vwrUcj4WXC_UbnLLWnalSzK49iBMoK
"""

!pip install git+https://github.com/huggingface/transformers.git

import torch
from PIL import Image
from transformers import pipeline

# 1. Initialize the DALL-E mini pipeline
# This model generates images from text prompts.
# The first time you run this, it will download the model, which might take a few minutes.
print("Initializing DALL-E mini model...")
generator = pipeline("text-to-image", model="dalle-mini/dalle-mini")
print("Model initialized!")

# 2. Define your text prompt
prompt = "A cat riding a bicycle in space, digital art"
print(f"\nGenerating an image for the prompt: '{prompt}'")

# 3. Generate the image
# You can adjust the num_inference_steps for faster (lower number) or higher quality (higher number) generation.
# Higher steps takes longer.
image_output = generator(prompt, num_inference_steps=50)

# The output is typically a list of PIL Image objects. We'll take the first one.
if image_output and len(image_output) > 0:
    generated_image = image_output[0]

    # 4. Display the generated image
    print("\nGenerated Image:")
    display(generated_image) # In Colab, 'display' shows the image directly.

    # Optional: Save the image
    # generated_image.save("dalle_mini_output.png")
    # print("Image saved as 'dalle_mini_output.png'")
else:
    print("No image was generated.")

"""### Switching to Stable Diffusion for Text-to-Image Generation

Given the persistent issues with DALL-E mini, we will now use Stable Diffusion, a powerful and widely adopted text-to-image model. This requires the `diffusers` library from Hugging Face.

First, we need to install the `diffusers` library, and optionally `accelerate` for faster inference.
"""

!pip install diffusers transformers accelerate

"""Now, let's set up the Stable Diffusion pipeline and generate an image. This might also involve downloading the model weights the first time, which can take some time depending on your internet connection."""

from diffusers import StableDiffusionPipeline
import torch
from PIL import Image

# 1. Load the pre-trained Stable Diffusion model
# This will download the model weights (around 4-7 GB) the first time it's run.
# We'll use a smaller, faster model for demonstration.
# Using 'stabilityai/stable-diffusion-2-1-base' as an example, you can explore others on Hugging Face.

# Check if CUDA is available for GPU acceleration, otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16 if device == "cuda" else torch.float32)
pipeline.to(device)
print("Stable Diffusion model loaded!")

# 2. Define your text prompt
prompt = "A cat riding a bicycle in space, digital art, high detail, vibrant colors"
print(f"\nGenerating an image for the prompt: '{prompt}'")

# 3. Generate the image
# You can adjust num_inference_steps for quality vs. speed. Guidance_scale influences how much the model follows the prompt.
image = pipeline(prompt, num_inference_steps=30, guidance_scale=7.5).images[0]

# 4. Display the generated image
print("\nGenerated Image:")
display(image)

# Optional: Save the image
# image.save("stable_diffusion_output.png")
# print("Image saved as 'stable_diffusion_output.png'")